import type { Metadata } from "next";
import "./globals.css";

// import components
import Drawer from "@/components/NavbarDrawer/Drawer";
import Footer from "@/components/Footer/Footer";


// config
import { getMenuForPath } from "@/utils/getMenuForPath";
import { headers } from "next/headers";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // ใช้ headers ดึง pathname ฝั่ง Server
  const headersList = await headers();
  const pathname = headersList.get("x-invoke-pathname") || "/"; // ค่าที่ Middleware ส่งมา (fallback เป็น "/")

  // ตรวจสอบว่าอยู่ในหน้า `/login` หรือไม่
  const isLoginPage = pathname === "/auth/secure/gateway/login";

  // ใช้ฟังก์ชัน Utility ดึงเมนูให้เหมาะสมกับ URL (เฉพาะหน้าอื่นที่ไม่ใช่ /login)
  const menu = isLoginPage ? null : getMenuForPath(pathname);

  return (
    <html lang="en" data-theme="light">
      <body className={`antialiased`}>
        {!isLoginPage && <Drawer menu={menu || []} pathname={pathname}/>}
        {children}
        {!isLoginPage && <Footer />}
      </body>
    </html>
  );
}
