import type { Metadata } from "next";
import "./globals.css";

// import components
import Navbar from "@/components/Navbar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" data-theme="garden">
      <body
        className={`antialiased h-[1500px]`}
      >
        <Navbar/>
        {children}
      </body>
    </html>
  );
}
