// ข้อมูลโหนดทั้งหมด
export const nodes = [
    {
      id: "1",
      position: { x: 799, y: 0 },
      data: { label: "สำนักสาธารณสุขและสิ่งแวดล้อม" },
      type: "customNode",
    },
    {
      id: "2",
      position: { x: 300, y: 150 },
      type: "customNode",
      data: { label: "ส่วนส่งเสริมสาธารณสุข" },
    },
    {
      id: "3",
      position: { x: 120, y: 250 },
      type: "customNode",
      data: { label: "ฝ่ายวิชาการและการประเมินผล" },
    },
    {
      id: "4",
      position: { x: 140, y: 350 },
      type: "customLeftNode",
      data: { label: "งานนโยบายและแผนงานสาธารณสุข" },
    },
    {
      id: "5",
      position: { x: 140, y: 450 },
      data: { label: "งานวิชาการและบริการข้อมูล" },
      type: "customLeftNode",
    },
    {
      id: "6",
      position: { x: 140, y: 550 },
      data: { label: "งานติดตามและประเมินผล" },
      type: "customLeftNode",
    },
    {
      id: "7",
      position: { x: 450, y: 250 },
      data: { label: "ฝ่ายส่งเสริมสาธารณสุข" },
      type: "customNode",
    },
    {
      id: "8",
      position: { x: 470, y: 350 },
      data: { label: "งานหลักประกันสุขภาพ" },
      type: "customLeftNode",
    },
    {
      id: "9",
      position: { x: 470, y: 450 },
      data: { label: "งานส่งเสริมคุณภาพชีวิตผู้สูงอายุ" },
      type: "customLeftNode",
    },
    {
      id: "10",
      position: { x: 470, y: 550 },
      data: { label: "งานอาสาสมัครสาธารณสุข" },
      type: "customLeftNode",
    },
    {
      id: "11",
      position: { x: 470, y: 650 },
      data: { label: "งานเผยแพร่และฝึกอบรมด้านสาธารณสุข" },
      type: "customLeftNode",
    },
    { id: "12", position: { x: 470, y: 750 }, data: { label: "งานสัตวแพทย์" }, type: "customLeftNode", },
    {
      id: "13",
      position: { x: 470, y: 850 },
      data: { label: "งานส่งเสริมสุขภาพ" },
      type: "customLeftNode",
    },
    {
      id: "14",
      position: { x: 470, y: 950 },
      data: { label: "งานป้องกันและควบคุมโรค" },
      type: "customLeftNode",
    },
    {
      id: "15",
      position: { x: 810, y: 150 },
      data: { label: "ส่วนบริการอนามัยสิ่งแวดล้อม" },
      type: "customNode",
    },
    {
      id: "16",
      position: { x: 803, y: 250 },
      data: { label: "ฝ่ายจัดการมูลฝอยและสิ่งปฏิกูล" },
      type: "customNode",
    },
    {
      id: "17",
      position: { x: 820, y: 350 },
      data: { label: "งานบริการรักษาความสะอาด" },
      type: "customLeftNode",
    },
    {
      id: "18",
      position: { x: 820, y: 450 },
      data: { label: "งานบริหารจัดการมูลฝอย" },
      type: "customLeftNode",
    },
    {
      id: "19",
      position: { x: 820, y: 550 },
      data: { label: "งานพัฒนาระบบจัดการมูลฝอย" },
      type: "customLeftNode",
    },
    {
      id: "20",
      position: { x: 820, y: 650 },
      data: { label: "งานบริหารจัดการสิ่งปฏิกูล" },
      type: "customLeftNode",
    },
    {
      id: "21",
      position: { x: 1137, y: 150 },
      data: { label: "ส่วนส่งเสริมอนามัยสิ่งแวดล้อม" },
      type: "customNode",
    },
    {
      id: "22",
      position: { x: 1100, y: 250 },
      data: { label: "ฝ่ายควบคุมและจัดการคุณภาพสิ่งแวดล้อม" },
      type: "customNode",
    },
    {
      id: "23",
      position: { x: 1120, y: 350 },
      data: { label: "งานสุขาภิบาลสถานประกอบการ" },
      type: "customLeftNode",
    },
    {
      id: "24",
      position: { x: 1120, y: 450 },
      data: { label: "งานสุขาภิบาลชุมชนเมืองและเหตุรำคาญ" },
      type: "customLeftNode",
    },
    {
      id: "25",
      position: { x: 1120, y: 550 },
      data: { label: "งานคุ้มครองผู้บริโภค" },
      type: "customLeftNode",
    },
    {
      id: "26",
      position: { x: 1120, y: 650 },
      data: { label: "งานเฝ้าระวังและตรวจสอบคุณภาพสิ่งแวดล้อม" },
      type: "customLeftNode",
    },
    {
      id: "27",
      position: { x: 1120, y: 750 },
      data: { label: "งานจัดการทรัพยากรธรรมชาติและสิ่งแวดล้อม" },
      type: "customLeftNode",
    },
    {
      id: "28",
      position: { x: 1450, y: 61 },
      data: { label: "ฝ่ายบริหารงานทั่วไป" },
      type: "customDubleLeftNode",
    },
    {
      id: "29",
      position: { x: 1470, y: 150 },
      data: { label: "งานบริหารทั่วไป" },
      type: "customLeftNode",
    },
    {
      id: "30",
      position: { x: 1470, y: 250 },
      data: { label: "งานการเงินและบัญชี" },
      type: "customLeftNode",
    },
  ];

 export const edges = [
    { id: "e1", source: "1", target: "2", style: { stroke: "var(--fallback-bc,oklch(var(--bc)/var(--tw-bg-opacity, 1)))"}, type: "step" },
    { id: "e2", source: "2", target: "3", style: { stroke: "var(--fallback-bc,oklch(var(--bc)/var(--tw-bg-opacity, 1)))"}, type: "step" },
    {
      id: "e3",
      source: "3",
      target: "4",
      style: { stroke: "var(--fallback-bc,oklch(var(--bc)/var(--tw-bg-opacity, 1)))"},
      type: "step",
      sourceHandle: "left",
    },
    {
      id: "e4",
      source: "3",
      target: "5",
      style: { stroke: "var(--fallback-bc,oklch(var(--bc)/var(--tw-bg-opacity, 1)))"},
      type: "step",
      sourceHandle: "left",
    },
    {
      id: "e5",
      source: "3",
      target: "6",
      style: { stroke: "var(--fallback-bc,oklch(var(--bc)/var(--tw-bg-opacity, 1)))"},
      type: "step",
      sourceHandle: "left",
    },
    {
      id: "e6",
      source: "2",
      target: "7",
      style: { stroke: "var(--fallback-bc,oklch(var(--bc)/var(--tw-bg-opacity, 1)))"},
      type: "step",
    },
    {
      id: "e7",
      source: "7",
      target: "8",
      style: { stroke: "var(--fallback-bc,oklch(var(--bc)/var(--tw-bg-opacity, 1)))"},
      type: "step",
      sourceHandle: "left",
    },
    {
      id: "e8",
      source: "7",
      target: "9",
      style: { stroke: "var(--fallback-bc,oklch(var(--bc)/var(--tw-bg-opacity, 1)))"},
      type: "step",
      sourceHandle: "left",
    },
    {
      id: "e9",
      source: "7",
      target: "10",
      style: { stroke: "var(--fallback-bc,oklch(var(--bc)/var(--tw-bg-opacity, 1)))"},
      type: "step",
      sourceHandle: "left",
    },
    {
      id: "e10",
      source: "7",
      target: "11",
      style: { stroke: "var(--fallback-bc,oklch(var(--bc)/var(--tw-bg-opacity, 1)))"},
      type: "step",
      sourceHandle: "left",
    },
    {
      id: "e11",
      source: "7",
      target: "12",
      style: { stroke: "var(--fallback-bc,oklch(var(--bc)/var(--tw-bg-opacity, 1)))"},
      type: "step",
      sourceHandle: "left",
    },
    {
      id: "e12",
      source: "7",
      target: "12",
      style: { stroke: "var(--fallback-bc,oklch(var(--bc)/var(--tw-bg-opacity, 1)))"},
      type: "step",
      sourceHandle: "left",
    },
    {
      id: "e13",
      source: "7",
      target: "13",
      style: { stroke: "var(--fallback-bc,oklch(var(--bc)/var(--tw-bg-opacity, 1)))"},
      type: "step",
      sourceHandle: "left",
    },
    {
      id: "e14",
      source: "7",
      target: "14",
      style: { stroke: "var(--fallback-bc,oklch(var(--bc)/var(--tw-bg-opacity, 1)))"},
      type: "step",
      sourceHandle: "left",
    },
    {
      id: "e15",
      source: "1",
      target: "15",
      style: { stroke: "var(--fallback-bc,oklch(var(--bc)/var(--tw-bg-opacity, 1)))"},
      type: "step",
      sourceHandle: "bottom",
    },
    {
      id: "e16",
      source: "15",
      target: "16",
      style: { stroke: "var(--fallback-bc,oklch(var(--bc)/var(--tw-bg-opacity, 1)))"},
      type: "step",
      sourceHandle: "bottom",
    },
    {
      id: "e17",
      source: "16",
      target: "17",
      style: { stroke: "var(--fallback-bc,oklch(var(--bc)/var(--tw-bg-opacity, 1)))"},
      type: "step",
      sourceHandle: "left",
    },
    {
      id: "e18",
      source: "16",
      target: "18",
      style: { stroke: "var(--fallback-bc,oklch(var(--bc)/var(--tw-bg-opacity, 1)))"},
      type: "step",
      sourceHandle: "left",
    },
    {
      id: "e19",
      source: "16",
      target: "19",
      style: { stroke: "var(--fallback-bc,oklch(var(--bc)/var(--tw-bg-opacity, 1)))"},
      type: "step",
      sourceHandle: "left",
    },
    {
      id: "e20",
      source: "16",
      target: "20",
      style: { stroke: "var(--fallback-bc,oklch(var(--bc)/var(--tw-bg-opacity, 1)))"},
      type: "step",
      sourceHandle: "left",
    },
    {
      id: "e21",
      source: "1",
      target: "21",
      style: { stroke: "var(--fallback-bc,oklch(var(--bc)/var(--tw-bg-opacity, 1)))"},
      type: "step",
    },
    {
      id: "e22",
      source: "21",
      target: "22",
      style: { stroke: "var(--fallback-bc,oklch(var(--bc)/var(--tw-bg-opacity, 1)))"},
      type: "step",
    },
    {
      id: "e23",
      source: "22",
      target: "23",
      style: { stroke: "var(--fallback-bc,oklch(var(--bc)/var(--tw-bg-opacity, 1)))"},
      type: "step",
      sourceHandle: "left",
    },
    {
      id: "e24",
      source: "22",
      target: "24",
      style: { stroke: "var(--fallback-bc,oklch(var(--bc)/var(--tw-bg-opacity, 1)))"},
      type: "step",
      sourceHandle: "left",
    },
    {
      id: "e25",
      source: "22",
      target: "25",
      style: { stroke: "var(--fallback-bc,oklch(var(--bc)/var(--tw-bg-opacity, 1)))"},
      type: "step",
      sourceHandle: "left",
    },
    {
      id: "e26",
      source: "22",
      target: "26",
      style: { stroke: "var(--fallback-bc,oklch(var(--bc)/var(--tw-bg-opacity, 1)))"},
      type: "step",
      sourceHandle: "left",
    },
    {
      id: "e27",
      source: "22",
      target: "27",
      style: { stroke: "var(--fallback-bc,oklch(var(--bc)/var(--tw-bg-opacity, 1)))"},
      type: "step",
      sourceHandle: "left",
    },
    {
      id: "e28",
      source: "1",
      target: "28",
      style: { stroke: "var(--fallback-bc,oklch(var(--bc)/var(--tw-bg-opacity, 1)))"},
      type: "step",
    },
    {
      id: "e29",
      source: "28",
      target: "29",
      style: { stroke: "var(--fallback-bc,oklch(var(--bc)/var(--tw-bg-opacity, 1)))"},
      type: "step",
      sourceHandle: "left2",
    },
    {
      id: "e30",
      source: "28",
      target: "30",
      style: { stroke: "var(--fallback-bc,oklch(var(--bc)/var(--tw-bg-opacity, 1)))"},
      type: "step",
      sourceHandle: "left2",
    },
  ];